In [ ]:
import numpy as np
a=np.array([10, 12, 13, 14])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np

p=np.array([[1, 2, 3],[4, 5, 6]])
print(p)
print(p.ndim)
print(p.shape)
print(p.size)


[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [ ]:
p=np.array([2, 3, 4, 5, 6])
print(p[-1])
p=np.array([[1, 2, 3],[4, 5, 6]])
print(p[0, -1])

6
3


In [ ]:
n=np.array([1, 2, 3, 4, 5, 6])
print(n.shape)
print(n.reshape(2, 3))

(6,)
[[1 2 3]
 [4 5 6]]


In [ ]:
n=np.aarray([1, 2, 3, 4])
m=np.array([4, 5, 6, 7])
